### ISSUE TITLE
Steps report should take real steps

### ISSUE THREAD

**Issue by edogab33** [SimoravaIT/Tamagotchi_Android#29]
![Schermata 2021-11-25 alle 11 17 24](https://user-images.githubusercontent.com/12884117/143423166-17acd025-5787-4d9a-9f08-3e695d122c39.png)

**Comment by SimoravaIT** [comment]
I implemented the part that change the "today step 6899" with the real value

**Comment by edogab33** [comment]
> I implemented the part that change the "today step 6899" with the real value

Alright, then we need to do that also for "Week Steps" and "Total Steps" (does it make sense to have the latter?).

Furthermore there is a typo in all the three visualizations: it is "stepS" not "step"

**Comment by SimoravaIT** [comment]
done for mounth, WIP for total.
@YuanjenHung can you change the typo graphically?

**Comment by SimoravaIT** [comment]
done also for the total counter, if we want to change the month count in like for example "last N days count" is just a variable to be changed.
